api_settings:
  api_key: "1ZhrKoaow3FeAZwoPXCHNPpq0LTKjK4G"
  base_url: "https://api.nytimes.com/svc/search/v2/articlesearch.json"
  topic: "artificial intelligence"

general_settings:
  cache_timeout: 3600  # in seconds
  max_articles: 100
